version: "3.9"

services:
  nginx:
    image: nginx:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - eodi-frontend-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/eodi/infra/prod/app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/eodi/infra/prod/app/nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/eodi/data/certbot/www:/var/www/certbot
      - /opt/eodi/data/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    mem_limit: 128m

networks:
  eodi-frontend-net:
    external: true
